#!/usr/bin/env node
/**
 * Generate a PostgreSQL schema from Base44 entity definitions (base44/entities/*.jsonc).
 *
 * Design: Base44 is a document store, so each entity becomes a table with a JSONB `data`
 * column holding all its properties, plus promoted system columns (id, created_date,
 * updated_date, created_by). A GIN index (jsonb_path_ops) makes equality/containment
 * filters fast — which is exactly what the code's .filter({field: value}) calls do.
 *
 * Usage: node tools/gen-schema.mjs <entities_dir> <out.sql>
 */
import fs from 'node:fs';
import path from 'node:path';

const [,, ENT_DIR, OUT] = process.argv;
if (!ENT_DIR || !OUT) { console.error('usage: gen-schema.mjs <entities_dir> <out.sql>'); process.exit(1); }

// Tolerant JSONC → JSON: strip /* */ and // comments that are NOT inside strings.
function stripJsonc(src) {
  let out = ''; let inStr = false; let strCh = ''; let i = 0;
  while (i < src.length) {
    const c = src[i], n = src[i+1];
    if (inStr) {
      out += c;
      if (c === '\\') { out += src[i+1] ?? ''; i += 2; continue; }
      if (c === strCh) inStr = false;
      i++; continue;
    }
    if (c === '"' || c === "'") { inStr = true; strCh = c; out += c; i++; continue; }
    if (c === '/' && n === '/') { while (i < src.length && src[i] !== '\n') i++; continue; }
    if (c === '/' && n === '*') { i += 2; while (i < src.length && !(src[i] === '*' && src[i+1] === '/')) i++; i += 2; continue; }
    out += c; i++;
  }
  return out;
}

const files = fs.readdirSync(ENT_DIR).filter(f => f.endsWith('.jsonc') || f.endsWith('.json'));
const SYSTEM = new Set(['id','created_date','updated_date','created_by']);
let sql = `-- PlayEarning Nexus — PostgreSQL schema (generated from ${files.length} Base44 entities)
-- Generated by tools/gen-schema.mjs. Document-store faithful port: properties live in JSONB "data".
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- for gen_random_uuid()

`;

let ok = 0, bad = [];
for (const f of files.sort()) {
  const raw = fs.readFileSync(path.join(ENT_DIR, f), 'utf8');
  let def;
  try { def = JSON.parse(stripJsonc(raw)); }
  catch (e) { bad.push(f + ' (' + e.message.slice(0,40) + ')'); continue; }
  const name = def.name || path.basename(f).replace(/\.jsonc?$/, '');
  const props = def.properties || {};
  const t = `"${name}"`;
  sql += `-- ${name}: ${Object.keys(props).length} properties\n`;
  sql += `CREATE TABLE IF NOT EXISTS ${t} (\n`;
  sql += `  id           text PRIMARY KEY DEFAULT gen_random_uuid()::text,\n`;
  sql += `  created_date timestamptz NOT NULL DEFAULT now(),\n`;
  sql += `  updated_date timestamptz NOT NULL DEFAULT now(),\n`;
  sql += `  created_by   text,\n`;
  if (name === 'User') {
    sql += `  email         text UNIQUE,\n`;
    sql += `  password_hash text,\n`;
    sql += `  role          text NOT NULL DEFAULT 'user',\n`;
  }
  sql += `  data         jsonb NOT NULL DEFAULT '{}'::jsonb\n`;
  sql += `);\n`;
  sql += `CREATE INDEX IF NOT EXISTS "${name}_data_gin" ON ${t} USING gin (data jsonb_path_ops);\n`;
  sql += `CREATE INDEX IF NOT EXISTS "${name}_created" ON ${t} (created_date DESC);\n\n`;
  ok++;
}

sql += `\n-- Auto-update updated_date on row change\nCREATE OR REPLACE FUNCTION set_updated_date() RETURNS trigger AS $$\nBEGIN NEW.updated_date = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;\n`;

fs.writeFileSync(OUT, sql);
console.log(`Generated ${ok} tables → ${OUT}`);
if (bad.length) { console.log(`SKIPPED ${bad.length} (parse issues):`); bad.slice(0,20).forEach(b => console.log('  - ' + b)); }
