// Row-Level Security enforcement for the USER-FACING entity routes.
// Loads db/rls-policy.json (generated by tools/rls-audit.mjs) and, for user-scoped
// entities, injects an owner filter so a signed-in user only sees their own rows.
// Backend functions use asServiceRole and bypass this entirely (leaderboards, admin, etc.).
type Policy = Record<string, { scope: "global" | "owner" | "self"; owner_field?: string }>;

let policy: Policy = {};
try {
  policy = JSON.parse(await Deno.readTextFile(new URL("../db/rls-policy.json", import.meta.url)));
} catch {
  console.warn("[rls] db/rls-policy.json not found — entity routes will run WITHOUT row scoping.");
}

export function entityScope(entity: string) {
  return policy[entity]?.scope ?? "global";
}

/** Merge the owner constraint into a query for reads. Returns the (possibly) scoped query. */
export function scopeQuery(entity: string, query: Record<string, unknown>, userId: string | null): Record<string, unknown> {
  const p = policy[entity];
  if (!p || p.scope === "global") return query;
  if (!userId) return query; // unauthenticated reads on scoped entities are handled by the route (401)
  if (p.scope === "self") return { ...query, id: userId };
  return { ...query, [p.owner_field ?? "user_id"]: userId };
}

/** Whether a write/read on this entity requires an authenticated user. */
export function requiresAuth(entity: string): boolean {
  return entityScope(entity) !== "global";
}
