// Hierarchical product taxonomy — designed to EXCEED a large retailer's browse structure.
//
// Three levels:
//   Level 1  TOP categories (departments)          — authored below (~40)
//   Level 2  subcategories                          — authored below (~900)
//   Level 3  browse nodes                           — AI-expanded per subcategory at scale (see
//            aiBrowseNodeExpand), producing tens of thousands of original browse nodes.
//
// The authored two levels alone rival a large retailer's browsable structure; the AI third level pushes
// the total node count past it. Everything here is ORIGINAL taxonomy (no retailer's data is copied).

export interface TopCategory { name: string; subs: string[]; }

export const TAXONOMY: TopCategory[] = [
  // Physical Items — a dedicated department for tangible goods the buyer receives, split by how they get
  // it: shipped to them, or picked up locally. Listed first so it gets a serverless-GPU category tile
  // (aiCategoryImages) exactly like every other department. The two fulfillment modes are subcategories
  // so they get their own tiles too.
  { name: "Physical Items", subs: ["Buy Online & Ship", "Local Pickup", "Electronics & Tech", "Home & Kitchen Goods", "Tools & Hardware", "Apparel & Footwear", "Health & Beauty", "Toys & Games", "Sports & Outdoors", "Automotive Parts"] },
  { name: "Electronics", subs: ["Headphones & Earbuds","Bluetooth Speakers","Home Audio","Portable Audio","Televisions","Streaming Devices","Home Theater Systems","Projectors","Soundbars","Turntables","Microphones","Amplifiers & Receivers","GPS & Navigation","Car Audio","Car Video","Dash Cams","Radar Detectors","Two-Way Radios","Digital Cameras","Mirrorless Cameras","DSLR Cameras","Action Cameras","Camera Lenses","Camera Tripods","Camera Flashes","Binoculars & Telescopes","Drones & Accessories","Wearable Technology","Smartwatches","Fitness Trackers","VR Headsets","eBook Readers","Batteries","Chargers & Power Banks","Surge Protectors","Cables & Adapters"] },
  { name: "Computers & Accessories", subs: ["Laptops","Gaming Laptops","2-in-1 Laptops","Desktops","All-in-One Computers","Mini PCs","Tablets","Monitors","Ultrawide Monitors","Keyboards","Mechanical Keyboards","Mice","Webcams","Docking Stations","USB Hubs","External Hard Drives","SSDs","Flash Drives","Memory Cards","RAM","CPUs","Graphics Cards","Motherboards","Power Supplies","PC Cases","CPU Coolers","Networking Routers","Mesh WiFi","Modems","Network Switches","Printers","Ink & Toner","Scanners","Laptop Bags","Laptop Stands"] },
  { name: "Cell Phones & Accessories", subs: ["Unlocked Phones","Smartphones","Basic Phones","Phone Cases","Screen Protectors","Phone Chargers","Wireless Chargers","Phone Mounts","PopSockets & Grips","Selfie Sticks","Phone Camera Lenses","Power Banks","SIM Cards","Smartwatch Bands","Bluetooth Headsets"] },
  { name: "Home & Kitchen", subs: ["Cookware Sets","Frying Pans","Saucepans","Dutch Ovens","Bakeware","Baking Sheets","Cutlery Sets","Kitchen Knives","Knife Sharpeners","Cutting Boards","Dinnerware Sets","Drinkware","Coffee Mugs","Water Bottles","Food Storage Containers","Kitchen Utensils","Mixing Bowls","Coffee Makers","Espresso Machines","Blenders","Food Processors","Air Fryers","Toasters","Microwave Ovens","Slow Cookers","Pressure Cookers","Stand Mixers","Kettles","Bedding Sets","Comforters","Sheets","Pillows","Mattress Toppers","Bath Towels","Shower Curtains","Bathroom Storage","Living Room Furniture","Sofas","Coffee Tables","TV Stands","Bedroom Furniture","Beds & Frames","Dressers","Nightstands","Mattresses","Office Chairs","Desks","Dining Sets","Home Décor","Wall Art","Mirrors","Clocks","Candles","Vases","Artificial Plants","Throw Pillows","Area Rugs","Curtains","Table Lamps","Floor Lamps","Ceiling Lights","LED Strip Lights"] },
  { name: "Home Improvement & Tools", subs: ["Power Drills","Impact Drivers","Circular Saws","Jigsaws","Angle Grinders","Sanders","Rotary Tools","Tool Sets","Screwdriver Sets","Wrench Sets","Socket Sets","Hammers","Pliers","Tape Measures","Levels","Tool Boxes","Tool Bags","Work Gloves","Safety Glasses","Fasteners & Screws","Wall Anchors","Adhesives & Tape","Extension Cords","Light Bulbs","LED Bulbs","Smart Bulbs","Ceiling Fans","Door Hardware","Smart Locks","Deadbolts","Plumbing Fixtures","Faucets","Shower Heads","Paint","Paint Brushes","Paint Rollers","Ladders","Wet/Dry Vacuums","Portable Generators","Air Compressors"] },
  { name: "Garden & Outdoor", subs: ["Planters","Raised Garden Beds","Garden Tools","Pruning Shears","Watering Hoses","Sprinklers","Seeds","Fertilizers","Potting Soil","Lawn Mowers","String Trimmers","Leaf Blowers","Hedge Trimmers","Chainsaws","Gas Grills","Charcoal Grills","Pellet Grills","Smokers","Grill Accessories","Patio Sets","Outdoor Chairs","Hammocks","Fire Pits","Outdoor Heaters","String Lights","Pool Floats","Pool Cleaning","Hot Tubs","Pest Control","Bird Feeders","Snow Blowers","Snow Shovels"] },
  { name: "Beauty & Personal Care", subs: ["Moisturizers","Facial Cleansers","Serums","Sunscreen","Face Masks","Anti-Aging","Foundation","Concealer","Lipstick","Mascara","Eyeshadow Palettes","Makeup Brushes","Shampoo","Conditioner","Hair Oil","Hair Dryers","Hair Straighteners","Curling Irons","Perfume","Cologne","Body Wash","Body Lotion","Deodorant","Hand Cream","Nail Polish","Manicure Sets","Electric Razors","Beard Trimmers","Shaving Cream","Electric Toothbrushes","Whitening","Facial Steamers"] },
  { name: "Health & Household", subs: ["Multivitamins","Protein Powder","Probiotics","Fish Oil","Vitamin D","Vitamin C","Collagen","Pre-Workout","Pain Relief","Cold & Flu","Allergy Relief","Digestive Health","Sleep Aids","Blood Pressure Monitors","Thermometers","Pulse Oximeters","First Aid Kits","Bandages","Hand Sanitizer","Disinfectant Wipes","Paper Towels","Toilet Paper","Trash Bags","Laundry Detergent","Dish Soap","Air Fresheners","Reading Glasses","Contact Solution","Mobility Aids","Massage Guns","Heating Pads","Braces & Supports"] },
  { name: "Grocery & Gourmet Food", subs: ["Coffee Beans","Ground Coffee","Coffee Pods","Tea","Snack Bars","Chips","Nuts","Dried Fruit","Chocolate","Candy","Cookies","Cereal","Oatmeal","Pasta","Rice","Canned Goods","Cooking Oil","Spices","Hot Sauce","Condiments","Honey","Nut Butters","Protein Snacks","Sparkling Water","Energy Drinks","Baby Food","Gluten-Free","Organic Foods","Vegan Foods"] },
  { name: "Baby", subs: ["Diapers","Baby Wipes","Diaper Bags","Baby Formula","Bottles","Bottle Warmers","Breast Pumps","High Chairs","Strollers","Travel Strollers","Car Seats","Booster Seats","Baby Carriers","Cribs","Bassinets","Changing Tables","Baby Monitors","Baby Gates","Nursing Pillows","Teethers","Baby Toys","Baby Clothing","Baby Bath","Pacifiers","Playpens"] },
  { name: "Toys & Games", subs: ["Action Figures","Building Blocks","Building Sets","Dolls","Dollhouses","Toy Cars","RC Cars","RC Drones","Board Games","Card Games","Puzzles","Jigsaw Puzzles","STEM Toys","Educational Toys","Arts & Crafts Kits","Play-Doh & Clay","Stuffed Animals","Plush Toys","Outdoor Toys","Trampolines","Play Kitchens","Train Sets","Science Kits","Slime & Putty","Fidget Toys","Collectible Figures","Trading Card Games","Party Games"] },
  { name: "Women's Fashion", subs: ["Dresses","Tops & Blouses","T-Shirts","Sweaters","Cardigans","Jeans","Pants","Leggings","Skirts","Shorts","Jackets","Coats","Blazers","Activewear","Sports Bras","Lingerie","Sleepwear","Swimwear","Heels","Flats","Boots","Sneakers","Sandals","Handbags","Crossbody Bags","Wallets","Belts","Scarves","Sunglasses","Jewelry Sets","Necklaces","Earrings"] },
  { name: "Men's Fashion", subs: ["T-Shirts","Polo Shirts","Dress Shirts","Sweaters","Hoodies","Jeans","Chinos","Dress Pants","Shorts","Jackets","Coats","Blazers","Suits","Activewear","Underwear","Socks","Swimwear","Sneakers","Dress Shoes","Boots","Sandals","Loafers","Wallets","Belts","Ties","Sunglasses","Watches","Backpacks","Messenger Bags"] },
  { name: "Kids & Baby Fashion", subs: ["Girls' Dresses","Girls' Tops","Girls' Bottoms","Boys' Shirts","Boys' Pants","Kids' Outerwear","Kids' Sleepwear","Kids' Shoes","Kids' Sneakers","School Uniforms","Kids' Activewear","Kids' Swimwear","Kids' Accessories","Baby Onesies","Toddler Sets"] },
  { name: "Shoes", subs: ["Running Shoes","Walking Shoes","Cross-Training Shoes","Basketball Shoes","Hiking Boots","Work Boots","Casual Sneakers","Dress Shoes","Loafers","Sandals","Flip Flops","Slippers","Rain Boots","Snow Boots","Cleats"] },
  { name: "Jewelry & Watches", subs: ["Necklaces","Pendants","Earrings","Stud Earrings","Bracelets","Bangles","Rings","Engagement Rings","Wedding Bands","Anklets","Brooches","Cufflinks","Men's Watches","Women's Watches","Smart Watches","Watch Bands","Jewelry Boxes","Body Jewelry"] },
  { name: "Sports & Outdoors", subs: ["Dumbbells","Kettlebells","Resistance Bands","Yoga Mats","Exercise Bikes","Treadmills","Rowing Machines","Weight Benches","Pull-Up Bars","Jump Ropes","Foam Rollers","Bicycles","Mountain Bikes","Road Bikes","Bike Helmets","Bike Locks","Tents","Sleeping Bags","Backpacks","Camping Stoves","Coolers","Water Bottles","Hydration Packs","Fishing Rods","Fishing Reels","Tackle","Kayaks","Paddle Boards","Basketballs","Soccer Balls","Golf Clubs","Golf Balls","Ski Gear","Snowboards","Skateboards"] },
  { name: "Automotive", subs: ["Motor Oil","Oil Filters","Air Filters","Wiper Blades","Car Batteries","Spark Plugs","Brake Pads","Car Wax","Car Wash Soap","Microfiber Towels","Tire Inflators","Jump Starters","Floor Mats","Seat Covers","Steering Wheel Covers","Phone Mounts","Dash Cams","Backup Cameras","Car Speakers","Car Stereos","Tires","Wheels","Roof Racks","Cargo Carriers","Tow Hitches","Motorcycle Helmets","Motorcycle Gear","Car Covers","Jacks & Stands","OBD2 Scanners"] },
  { name: "Pet Supplies", subs: ["Dog Food","Dry Dog Food","Wet Dog Food","Dog Treats","Dog Beds","Dog Crates","Dog Collars","Dog Leashes","Dog Harnesses","Dog Toys","Cat Food","Cat Litter","Litter Boxes","Cat Trees","Cat Toys","Scratching Posts","Aquariums","Fish Food","Aquarium Filters","Bird Cages","Bird Food","Small Animal Habitats","Reptile Terrariums","Pet Grooming","Flea & Tick","Pet Carriers","Pet Gates","Automatic Feeders","Pet Cameras"] },
  { name: "Office Products", subs: ["Pens","Pencils","Markers","Highlighters","Notebooks","Sticky Notes","Printer Paper","Envelopes","Binders","Folders","File Cabinets","Desk Organizers","Staplers","Tape Dispensers","Scissors","Label Makers","Whiteboards","Calendars","Planners","Calculators","Shredders","Laminators","Desk Accessories","Ergonomic Accessories"] },
  { name: "Books", subs: ["Fiction","Mystery & Thriller","Science Fiction","Fantasy","Romance","Literary Fiction","Nonfiction","Biographies","History","Self-Help","Business","Cookbooks","Health & Fitness","Travel Guides","Children's Books","Young Adult","Comics & Graphic Novels","Textbooks","Test Prep","Religion & Spirituality","Art & Photography","Science & Math","Reference"] },
  { name: "Movies, Music & Media", subs: ["Blu-ray Movies","DVD Movies","4K Ultra HD","TV Series Box Sets","Vinyl Records","Music CDs","Music Boxsets","Documentaries","Anime","Video Game Soundtracks"] },
  { name: "Video Games", subs: ["PlayStation 5 Games","Xbox Series X Games","Nintendo Switch Games","PC Games","Game Consoles","Handheld Consoles","Controllers","Gaming Headsets","Gaming Keyboards","Gaming Mice","Gaming Chairs","Gaming Monitors","VR Games","Game Gift Cards","Console Accessories","Retro Gaming"] },
  { name: "Musical Instruments", subs: ["Acoustic Guitars","Electric Guitars","Bass Guitars","Guitar Amps","Guitar Pedals","Guitar Strings","Digital Pianos","Keyboards","Synthesizers","MIDI Controllers","Acoustic Drums","Electronic Drums","Cymbals","Drumsticks","Microphones","Audio Interfaces","Studio Monitors","Studio Headphones","Violins","Ukuleles","Wind Instruments","DJ Controllers","Mixers","Cables & Stands"] },
  { name: "Arts, Crafts & Sewing", subs: ["Acrylic Paint","Watercolor Paint","Oil Paint","Paint Brushes","Sketchbooks","Colored Pencils","Markers","Canvas","Easels","Sewing Machines","Sewing Kits","Fabric","Yarn","Knitting Needles","Crochet Hooks","Embroidery","Beads","Jewelry Making Kits","Scrapbooking","Stickers","Craft Paper","Glue Guns","Cricut & Cutting Machines","Diamond Painting"] },
  { name: "Industrial & Scientific", subs: ["Lab Equipment","Microscopes","Safety Gloves","Safety Goggles","Hard Hats","Respirators","Hi-Vis Clothing","Janitorial Supplies","Industrial Adhesives","Fasteners","Bearings","Hydraulics","Pneumatics","Material Handling","Hand Trucks","Shelving","Workbenches","Multimeters","Oscilloscopes","Calipers","3D Printers","3D Printer Filament","Label Printers","Barcode Scanners"] },
  { name: "Appliances", subs: ["Refrigerators","Mini Fridges","Freezers","Wine Coolers","Washing Machines","Dryers","Washer Dryer Combos","Dishwashers","Ranges","Wall Ovens","Cooktops","Range Hoods","Over-the-Range Microwaves","Water Heaters","Water Filters","Garbage Disposals","Ice Makers","Dehumidifiers","Portable Air Conditioners","Window Air Conditioners","Space Heaters"] },
  { name: "Smart Home", subs: ["Smart Speakers","Smart Displays","Voice Assistants","Smart Bulbs","Smart Plugs","Smart Switches","Smart Thermostats","Video Doorbells","Security Cameras","Indoor Cameras","Outdoor Cameras","Smart Locks","Alarm Systems","Motion Sensors","Smart Blinds","Robot Vacuums","Robot Mops","Smart Garage Openers","Smart Sprinklers","Home Automation Hubs"] },
  { name: "Software", subs: ["Antivirus","VPN Services","Office Suites","Photo Editing","Video Editing","Operating Systems","Tax Software","Accounting Software","Design Software","Programming Tools","Language Learning","Educational Software","Utilities","Backup Software","Music Production"] },
  { name: "Luggage & Travel", subs: ["Carry-On Luggage","Checked Luggage","Luggage Sets","Spinner Suitcases","Backpacks","Travel Backpacks","Duffel Bags","Weekender Bags","Garment Bags","Packing Cubes","Travel Pillows","Toiletry Bags","Travel Adapters","Luggage Tags","Passport Holders","Travel Bottles","Money Belts"] },
  { name: "Handmade", subs: ["Handmade Jewelry","Handmade Earrings","Handmade Necklaces","Handmade Home Décor","Handmade Candles","Handmade Soap","Handmade Bags","Handmade Clothing","Handmade Pottery","Handmade Wall Art","Personalized Gifts","Custom Portraits","Handmade Toys","Handmade Stationery"] },
  { name: "Collectibles & Fine Art", subs: ["Coins","Paper Money","Stamps","Trading Cards","Sports Cards","Comic Books","Action Figure Collectibles","Model Kits","Die-Cast Models","Autographs","Sports Memorabilia","Vintage Advertising","Fine Art Prints","Paintings","Sculptures","Antiques"] },
  { name: "Party & Occasions", subs: ["Balloons","Party Decorations","Banners","Tableware","Party Favors","Gift Wrap","Gift Bags","Greeting Cards","Birthday Supplies","Wedding Supplies","Holiday Decorations","Christmas Decorations","Halloween Costumes","Costume Accessories","Candles","Party Games"] },
  { name: "Furniture", subs: ["Sofas & Couches","Sectionals","Recliners","Accent Chairs","Coffee Tables","End Tables","TV Stands","Bookshelves","Beds","Headboards","Mattresses","Dressers","Nightstands","Wardrobes","Dining Tables","Dining Chairs","Bar Stools","Office Desks","Office Chairs","Filing Cabinets","Outdoor Furniture","Patio Sets","Storage Cabinets","Shoe Racks","Coat Racks"] },
  { name: "Lighting", subs: ["Table Lamps","Floor Lamps","Desk Lamps","Ceiling Lights","Chandeliers","Pendant Lights","Wall Sconces","Track Lighting","Recessed Lighting","LED Strip Lights","String Lights","Night Lights","Outdoor Lighting","Solar Lights","Landscape Lighting","Flood Lights","Smart Lighting","Lamp Shades","Light Bulbs"] },
  { name: "Bedding & Bath", subs: ["Comforter Sets","Duvet Covers","Quilts","Bed Sheets","Pillowcases","Bed Pillows","Memory Foam Pillows","Mattress Protectors","Mattress Toppers","Blankets","Throw Blankets","Weighted Blankets","Bath Towels","Hand Towels","Washcloths","Bath Robes","Shower Curtains","Bath Mats","Bathroom Rugs","Bathroom Storage"] },
  { name: "Kitchen & Dining", subs: ["Cookware Sets","Nonstick Pans","Cast Iron","Stainless Steel Cookware","Bakeware Sets","Cake Pans","Muffin Pans","Knife Sets","Chef Knives","Cutting Boards","Dinnerware Sets","Flatware Sets","Glassware","Wine Glasses","Coffee Mugs","Travel Mugs","Water Bottles","Food Storage","Lunch Boxes","Kitchen Utensils","Measuring Cups","Mixing Bowls","Colanders","Kitchen Shears","Aprons","Oven Mitts","Dish Racks","Trash Cans"] },
  { name: "Photography", subs: ["Mirrorless Cameras","DSLR Cameras","Point & Shoot Cameras","Instant Cameras","Camera Lenses","Prime Lenses","Zoom Lenses","Tripods","Camera Bags","Memory Cards","Camera Batteries","External Flashes","Lighting Kits","Ring Lights","Green Screens","Gimbals","Camera Straps","Lens Filters","Photo Printers","Photo Frames"] },
  { name: "Office & Business Electronics", subs: ["Laser Printers","Inkjet Printers","All-in-One Printers","Scanners","Shredders","Laminators","Projectors","Conference Cameras","Headsets","Label Printers","UPS Battery Backups","Cash Registers","Receipt Printers","Barcode Scanners","Time Clocks"] },
  { name: "Wellness & Relaxation", subs: ["Massage Guns","Massage Chairs","Foot Massagers","Neck Massagers","Essential Oils","Diffusers","Aromatherapy","Meditation Cushions","Acupressure Mats","Heating Pads","Ice Packs","Sleep Masks","White Noise Machines","Weighted Blankets","Posture Correctors","Foam Rollers"] },
];

/** All subcategories flattened (level 2) — used to spread the AI seed catalog across breadth. */
export function allSubcategories(): string[] {
  return [...new Set(TAXONOMY.flatMap((t) => t.subs))];
}
/** Top-level category names (level 1). */
export function topCategoryNames(): string[] { return TAXONOMY.map((t) => t.name); }
/** Subcategories of a top category. */
export function subcategoriesOf(name: string): string[] {
  const c = TAXONOMY.find((t) => t.name.toLowerCase() === (name || "").toLowerCase());
  return c ? c.subs : [];
}
/** Totals, for reporting how far the taxonomy reaches. */
export function taxonomyCounts(): { categories: number; subcategories: number } {
  return { categories: TAXONOMY.length, subcategories: allSubcategories().length };
}
